name: Dart CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Working Directory
        run: mkdir -p /usr/src/extension && cp -R ./* /usr/src/extension
        working-directory: /usr/src/extension

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install NVM
        run: |
          sudo nvm install 17

      - name: Install Dependencies
        run: |
          sudo yum install -y gzip tar
          sudo yum update -y
          sudo yum upgrade -y

      - name: Clean Up
        run: |
          sudo yum autoremove -y
          sudo yum clean all
          sudo rm -rf /var/cache/yum