name: Dart CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup working Directory
        run: |
          sudo mkdir -p /usr/src/extension
          sudo cp -R ./* /usr/src/extension
          cd /usr/src/extension

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - run: |
          mkdir -p artifacts
          echo "" > artifacts/file.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: artifacts/file.txt