name: "Update Node Dependencies"

on:
  workflow_dispatch:
  schedule:
    # Runs at 12:30 (GMT), which is 06:30 (CST), Monday through Friday.
    - cron: "30 12 * * MON-FRI"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  update-deps:
    # prevent this scheduled action from running on forks
    uses: Workiva/gha-ts/.github/workflows/update-deps.yaml@v0.1.34
    with:
      package-path: .
      team-reviewers: fedx
